### ISSUE TITLE
Sandbox executable not found when installed from Git via Cargo

### ISSUE THREAD

**Issue by cairomassimo** [edomora97/task-maker-rust#2]
Install as follows:

```
cargo install task-maker-rust --git https://github.com/edomora97/task-maker-rust.git
```

then run `task-maker` in a task directory.

Worker threads panic with a `NotFound` error, probably related to `tmbox` not found in `PATH`, and print error messages on console. The process hangs.

**Comment by edomora97** [comment]
Fixed with 3c6e73f

Please note that only the hanging bit has been fixed: for sure task-maker should never hang, but it's your duty to install it correctly.
Unfortunately cargo is not yet able to install build artefacts (https://github.com/rust-lang/cargo/issues/2729), so `cargo install` is not able to bring `tmbox` in the `$PATH`.
