### ISSUE TITLE
Communication task problems

### ISSUE THREAD

**Issue by veluca93** [edomora97/task-maker-rust#63]
- Communication with a generator is not supported
- If the solution TLEs but the manager still reports 1.0, tmr assigns non0 to the subtask anyway.

**Comment by edomora97** [comment]
> Communication with a generator is not supported

Very interesting, I'll take a look soon.

> If the solution TLEs but the manager still reports 1.0, tmr assigns non0 to the subtask anyway.

It's a bug to me as well. If the solution doesn't exit within the time limit, it should get a TLE, regardless of the fact that it managed to provide the output to the manager in time. This is especially true under task-maker because we cannot check if the solution provided the answer within the TL, or just between the TL and the wall TL.

For completeness, this is the current behavior of a solution that prints the correct answer in the `communication_stdin` test, but then gets stuck in a infinite loop:

![image](https://user-images.githubusercontent.com/6685454/183980336-ee49ea4e-ce83-4160-b2f3-14d350980dd9.png)

Will fix this in a upcoming PR.

**Comment by edomora97** [comment]
Apparently this was a known issue:

https://github.com/edomora97/task-maker-rust/blob/f8b91616d01b309e29e9bb22d976b30f839bd432/task-maker-format/src/ioi/dag/task_type/communication.rs#L233-L237
